version: '3.8'

services:
  redis:
    image: 'redis:7.0.7-alpine'
    container_name: redis
    command: redis-server
    volumes:
      - redis_data:/data
    expose:
      - 6379
    logging:
      driver: "json-file"
      options:
        max-size: "512m"

  postgres:
    image: postgres:14.6
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - postgres_data:/var/lib/postgresql
    expose:
      - 5432
    logging:
      driver: "json-file"
      options:
        max-size: "512m"

  blockscout:
    depends_on:
      - postgres
      - smart-contract-verifier
      - redis
    # image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        SECRET_KEY_BASE: 'DigBd6xC1u6dMa1TyQ4UkG1yaltQATbGg6qapfWwCkvLyUYnWMlwIzG9XDY0aP0R'
    restart: always
    container_name: 'blockscout'
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    # command: bash -c "while true; do sleep 15 ; echo "background"; done"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - ./envs/common-godwoken.env
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: https://godwoken-testnet-v1.ckbapp.dev
      CHAIN_ID: '71401'
      SUPPORTED_CHAINS: '[ { "title": "Godwoken V1 Testnet", "url": "http://54.165.34.246:4000", "test_net?": true } ]'
      EXTERNAL_APPS: '[ { "title": "Faucet", "url": "https://homura.github.io/light-godwoken" }, { "title": "Aggron Explorer", "url": "https://v1.aggron.gwscan.com" } ]'
      BLOCKSCOUT_HOST: 'gw-explorer.nervosdao.community'
      SHOW_TESTNET_LABEL: 'true'
    ports:
      - 0.0.0.0:4000:4000
    volumes:
      - logs_data:/app/logs/
    logging:
      driver: "json-file"
      options:
        max-size: "512m"

  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:${SMART_CONTRACT_VERIFIER_DOCKER_TAG:-latest}
    restart: always
    container_name: 'smart-contract-verifier'
    env_file:
      - ./envs/common-smart-contract-verifier.env
    expose:
      - 8043

  visualizer:
    image: ghcr.io/blockscout/visualizer:${VISUALIZER_DOCKER_TAG:-latest}
    restart: always
    container_name: 'visualizer'
    env_file:
      - ./envs/common-visualizer.env
    expose:
      - 8050
    logging:
      driver: "json-file"
      options:
        max-size: "512m"

volumes:
  redis_data:
  postgres_data:
  logs_data:
